#!/bin/sh
getGitStatus() {
	echo
	cd $1/..
	pwd
	git fetch --all 2>/dev/null
	git status -s -b 2>/dev/null
}

export -f getGitStatus
find usrsettings usrdoc usrdev -name .git -type d -exec sh -c 'getGitStatus "$1"' _ {} \;