#!/bin/sh

#
# extract mail parts
#
awk -v filehead=$1.head -v filebody=$1.body -v filemime=$1.mime '
  BEGIN { body = 0; mime = 0; }
  body == 0 {
    if( match($0, /^$/) ) {
      body = 1;
      next;
    }
    if( mime == 0 ) {
      if( match(tolower($0), /^content-type/ ) ) {
        mime = 1;
      }
    } else if( mime == 1 ) {
      if( match($0, /^\w/) ) {
        mime = 2;
      }
    }
    if( mime == 1 ) {
      print >> filemime;
    } else {
      print >> filehead;
    }
  }
  body == 1 {
    print >> filebody;
  }
' $1.in

#
# create full mime multipart body
#
{
  cat $1.mime
  echo
  cat $1.body
} >$1.fullbody

#
# sign body
#
SENDER=$(echo "$2" | cut -d"<" -f2 | cut -d">" -f1)
PASSPHRASE=$(grep "$SENDER" /etc/postfix/autosign-passwd | cut -d":" -f2)
gpg2 --batch --pinentry-mode loopback --passphrase "$PASSPHRASE" -u "$2" --detach-sign -t -a -o $1.asc <$1.fullbody

if [ -f $1.asc ] ; then
  #
  # signing ok => recombine header and signed body
  #
  {
    cat $1.head
    echo "Content-Type: multipart/signed;"
    echo "  boundary=\"----PGP-SIG----\";"
    echo "  protocol=\"application/pgp-signature\""
    echo
    echo "------PGP-SIG----"
    cat $1.fullbody
    echo
    echo "------PGP-SIG----"
    echo
    echo "Content-Type: application/pgp-signature"
    echo
    cat $1.asc
    echo
    echo "------PGP-SIG------"
  } >$1.out
else
  #
  # signing failed => copy input to output
  #
  cp $1.in $1.out
fi
