#!/bin/sh

# Simple shell-based filter. It is meant to be invoked as follows:
#       /path/to/script -f sender recipients...

# Localize these. The -G option does nothing before Postfix 2.3.
INSPECT_DIR=/var/spool/autosign

# Here you must use the postfix sendmail program. The real sendmail will create an infinite loop.
# The installation may not touch /usr/bin/sendmail but create its own: /usr/bin/sendmail.postfix
SENDMAIL="/usr/sbin/sendmail.postfix -G -i" # NEVER NEVER NEVER use "-t" here.

# Exit codes from <sysexits.h>
EX_TEMPFAIL=75
EX_UNAVAILABLE=69

# Clean up when done or when aborting.
trap "rm -f $$.*" 0 1 2 3 15

# Start processing.
cd $INSPECT_DIR || {
    echo $INSPECT_DIR does not exist; exit $EX_TEMPFAIL; }

cat >$$.in || { 
    echo Cannot save mail to file; exit $EX_TEMPFAIL; }

# Specify your content filter here. Since we cd'ed into $INSPECT_DIR, we use the full path here.
/opt/autosign/autosign-action $$ $1

if [ -f $$.out ]; then
  $SENDMAIL "$@" <$$.out
fi

exit $?
