#!/bin/sh

getGitStatus() {
	echo
	cd $1/..
	pwd
	git fetch --all 2>/dev/null
	git status -s 2>/dev/null
	git branch -avvv 2>/dev/null
}
export -f getGitStatus

find $GITSTAT_REPOLIST -type d -name .git -not -path "*/thirdparty/*" -exec sh -c 'getGitStatus "$1"' _ {} \;
